### ISSUE TITLE
Deprecate svelteconfig.compiler

### ISSUE THREAD

**Issue by DeMoorJasper** [orlov-vo/parcel-transformer-svelte#11]
Svelte has just received some official guidelines on how to format and name the config.

You can find more information here: https://github.com/sveltejs/svelte/issues/1101#issuecomment-708104278

For this plugin it comes down to deprecating `compiler` in favor of `compilerOptions`

Parcel 1 plugin has already been updated to reflect this change: https://github.com/DeMoorJasper/parcel-plugin-svelte/pull/151

**Comment by orlov-vo** [comment]
Thank you! It's released in [v1.0.6](https://www.npmjs.com/package/parcel-transformer-svelte/v/1.0.6)
