### ISSUE TITLE
Incompatible with `svelte-routing`: `'Svelte config should be an object.'`

### ISSUE THREAD

**Issue by erincar** [orlov-vo/parcel-transformer-svelte#18]
Hello,

Thanks for this project.
I have been using this library for a personal project, to bind Parcel 2, Svelte 3, TailwindCSS and other PostCSS functionalities.

I installed `svelte-routing` on my project and simply added the import line to my `App.svelte`:
```js
import { Router, Link, Route } from "svelte-routing";
```

However, the `loadConfig.js` seemed unable to parse the `"svelte"` options of this library, which resides in their `package.json` and is simply `"svelte": "src/index.js"`.

I assume that this usage is legit, so maybe the config loader should either ignore this library or be able to load from file path.

[Here](https://github.com/EmilTholin/svelte-routing) is the repo for reference.

Thanks!

**Comment by jianzhou520** [comment]
same problem. I tried many other routings, none of these can worked.

**Comment by BAPostma** [comment]
With my PR #26 this issue is fixed and can be closed.
@orlov-vo Would you mind pushing a new release to NPM for this fix please? Thanks!

**Comment by orlov-vo** [comment]
@erincar @BAPostma I've released it in v1.2.3 to npm

**Comment by erincar** [comment]
Appreciated! Best.
