### ISSUE TITLE
Emits empty CSS file

### ISSUE THREAD

**Issue by mischnic** [orlov-vo/parcel-transformer-svelte#2]
With this input, an empty css file is emitted:
```html
<script>

</script>

<div>Hello Svelte!</div>
```

I'm guessing `css` is always an object?

https://github.com/orlov-vo/parcel-transformer-svelte/blob/3b9bed654ad596b93d199aa3959b19b03aa32395/index.js#L62-L65

**Comment by ricochet1k** [comment]
I've got a fix for this already. Waiting on #3

**Comment by orlov-vo** [comment]
Thanks guys! It will be released in `1.0.3` today
