### ISSUE TITLE
SourceMap.addRawMappings was changed to SourceMap.addVLQMap

### ISSUE THREAD

**Issue by rraallvv** [orlov-vo/parcel-transformer-svelte#20]
https://github.com/parcel-bundler/source-map/commit/ccc0eecbd51e2e55f104e8f77ca5507160129a20#diff-fc4400faf3d4e5dc260120ddbfc4d3c770e526224337e0e7823789f70ccab5f0

**Comment by orlov-vo** [comment]
fixed and released in [v1.1.2](https://github.com/orlov-vo/parcel-transformer-svelte/releases/tag/v1.1.2)
