### ISSUE TITLE
Assets not resolved

### ISSUE THREAD

**Issue by louis77** [orlov-vo/parcel-transformer-svelte#25]
Hi there
I'm using Parcel with the following config:
```js
{
  "extends": ["@parcel/config-default"],
  "transformers": {
    "*.svelte": ["parcel-transformer-svelte"],
    "*.hbs": ["@anikin/parcel-transformer-handlebars-precompile"]
  }
}
```
It looks like the assets used in Svelte files (pngs etc.) are not resolved and bundled like the assets used in plain html/js files. Is there any configuration that needs to be done to accomplish this?

**Comment by orlov-vo** [comment]
@louis77 Hi! Can you create a minimal reproducible example and publish it to some repo?
