### ISSUE TITLE
SourceMap.fromRawSourceMap is not a function

### ISSUE THREAD

**Issue by mathiasrw** [orlov-vo/parcel-transformer-svelte#6]
When doing `parcel build src/index.html` i get the following error: 

    parcel-transformer-svelte: SourceMap.fromRawSourceMap is not a function
	TypeError: SourceMap.fromRawSourceMap is not a function
    at Object.transform (/simple/node_modules/parcel-transformer-svelte/index.js:60:30) 
    at async runTransformer (/simple/node_modules/@parcel/core/lib/Transformation.js:483:3)

Looking at the different other plugins for parcel2 is looks like the way SourceMap is used has changed since the current implementation:

- https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/typescript-types/src/TSTypesTransformer.js#L142-L146

- https://github.com/parcel-bundler/parcel/blob/v2/packages/optimizers/cssnano/src/CSSNanoOptimizer.js#L40-L42

- https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/coffeescript/src/CoffeeScriptTransformer.js#L21-L31

- https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/less/src/LessTransformer.js#L56-L62

**Comment by w7it** [comment]
Thanks for reporting! The error should go away in new 1.0.4 version
