### ISSUE TITLE
Duplicated CSS

### ISSUE THREAD

**Issue by canadaduane** [orlov-vo/parcel-transformer-svelte#8]
@jsonkao reported this same issue in `parcel-plugin-svelte` for Parcel 1.x:

https://github.com/DeMoorJasper/parcel-plugin-svelte/issues/138

I've made a reproducible test case, based on his original case here: https://github.com/canadaduane/svelte-parcel-duplicate-styles

From jsonkao:

Styles are being duplicated. In a Svelte component like…

```
<div></div>

<style>
  div {
    background: red;
    width: 100px;
    height: 100px;
  }
</style>
```

…DevTools shows these styles:

<img width="741" alt="image" src="https://user-images.githubusercontent.com/129/93689202-6e869a00-fa89-11ea-88dd-07c476925b6a.png">

**Comment by canadaduane** [comment]
See also https://github.com/sveltejs/sapper/issues/1076 which inspired the fix.

**Comment by squirrelsquirrel78** [comment]
Hi! Coming back to this issue three years later lol… what if I _do_ want CSS inlined? And I don't at all want the `<link>` to reference a diferent stylesheet?
